packages:
  - backend
  - webapp
  - shared

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': false
  '@sentry/cli': false
  core-js: false
  esbuild: false
  prisma: false
  unrs-resolver: false

overrides:
  resolve: 1.22.12
